app = "sarafa-frontend"  # Unique app name
primary_region = "bom"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[statics]]
guest_path = "landing-page/web/html/mysarafa"  # Path to your static files
url_prefix = "/"  # Serve at root
