app = "mySarafa"
primary_region = "bom"

[build]
builder = "paketobuildpacks/builder:base"
[build.args]
OUTPUT_DIR = "landing-page/web/html/Mysarafa"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[statics]]
guest_path = "/"
url_prefix = "/"
