app = "mysarafa" 
primary_region = "bom"

[build]
builder = "paketobuildpacks/builder:base"


[http_service]
internal_port = 8080
force_https = true
[[http_service.ports]]
port = 8080
auto_stop_machines = false
min_machines_running = 1
