app = "sarafa-frontend" 
primary_region = "bom"

[build]
builder = "heroku/buildpack-nodejs"

[http_service]
internal_port = 8080
force_https = true
[[http_service.ports]]
port = 8080
auto_stop_machines = false
min_machines_running = 1