app = "mysarafa" 
primary_region = "bom"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# [build]
# builder = "paketobuildpacks/builder:base"


# [http_service]
# internal_port = 8080
# force_https = true
# [[http_service.ports]]
# port = 8080
# auto_stop_machines = false
# min_machines_running = 1
